### ISSUE TITLE
New Registry: Non-admins can't view the dashboard

### ISSUE THREAD

**Issue by calbertan** [bcgov/platform-services-registry#1027]
When logged in as a normal user, requests dont show up in the private and public cloud dashboard. Creating requests also doesn't properly create a request. The main issue is that the email is passed as userId in some parts

Definition of done:
- [x] requests show up in the dashboard - email is passed instead of userId

- [x] user can create requests - email is case sensitive

- [x] create Jest test cases to verify results

**Comment by funtigr** [comment]
The regular user can create a product and see it in the list:
<img width="864" alt="image" src="https://github.com/bcgov/platform-services-registry/assets/43115082/7985a314-3721-4699-9f3e-391c82579140">
However he can see all other products too as if he was an admin.
<img width="864" alt="image" src="https://github.com/bcgov/platform-services-registry/assets/43115082/d43133ff-be2b-4708-9421-6bd863c28bb9">
When he doesn't have any products he can't see any products but after he's mentioned in one of them he can see all of them.

> "email is case sensitive"
The above is mitigated by the Provisioner which makes contacts lowercase. If we want to this to take effect we need to change the Provisioner code as well.

**Side note**: 
First page of pagination is showing "0-10" and second page is showing "10-...".

**Comment by funtigr** [comment]
The issue mentioned in the previous comment is not a bug because it actually mentions the Platform.Services.Test.Account as a TL. 
We went through the Tests with Christopher.
I've created a separate bug ticket for the Side note from the previous comment - link:
https://app.zenhub.com/workspaces/app-dev-team-646fdb4400ed8c0021aceeb4/issues/gh/bcgov/platform-services-registry/1112
