### ISSUE TITLE
Update Mautic subscription 

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#1069]
to subscribe users to critical updates separately public and private cloud on Mautic side, need to send platform & cluster/provider name instead of segment name to Mautic

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaExyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3b138336e9e5a4eebe384440384f52fbe0ab560a/image.png)
 
https://github.com/bcgov/Mautic-Subscription-App/blob/3605d7be93c0ca987537953a656969ee0d143f21/docs/registry-mautic-integration.md

DoD
 - [ ]  Mautic gets platform and cluster/provider names

**Comment by funtigr** [comment]
I looked through the code. Mautic subscribe endpoint now gets three fields instead of one as it was before.
@Kolezhanchik 
My only concern is we were sending email and now we are sending user (reflected on the screenshot). 
Does Mautic already have this user email or will it get it from the user object?
<img width="384" alt="image" src="https://github.com/bcgov/platform-services-registry/assets/43115082/87487e7a-c443-460a-85e3-03b1dbb04a2c">

**Comment by funtigr** [comment]
After consultation it is clear that corresponding changes on Mautic side are yet to be implemented so no ability to test it now.
