### ISSUE TITLE
Create documentation about the landing page sensor

### ISSUE THREAD

**Issue by okanji** [bcgov/platform-services-registry#1302]
There is a sensor created by Billy that periodically looks specific html on the registry landing page to determine if the registry is available (i.e it has not crashed).

Create some documentation to notify developers of this when they change the landing page code.

DOD:

- [ ] Add documentation to the readme
- [ ] Add a comment in the code

**Comment by Amritpal-Nijjar** [comment]
Met with Billy, public documentation could be a security concern...

**Comment by okanji** [comment]
@Amritpal-Nijjar thanks for meeting with Billy about the sensor. If Billy feels that we should not document the sensor in our public repo that is fine and you can close that ticket. Make sure to explain that in the ticket its self before you close it. Thanks!

**Comment by Amritpal-Nijjar** [comment]
Because public documentation of the sensor could be a security concern, there is still merit in having updated documentation that is internal. I was not able to find anything current. Possibly create a ticket that addresses this.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMi94QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cccca89a8eb3e8c14156f60916d22c0a5e82562f/Screenshot%202023-11-20%20at%202.46.01%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0R4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a7caeb843bba49097ea051c23b9c39b8fb04fcad/Screenshot%202023-11-20%20at%202.47.40%20PM.png)
