### ISSUE TITLE
add functionality delete user for every of aws-roles 

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#1681]
add functionality to delete user to all of aws-roles via icon and modal winnow according to provided Figma mock up
https://www.figma.com/file/llP34TwOrBUjUGey9PUu6c/Platform-Registry?type=design&node-id=2128-9380&mode=design&t=9xM4LTrJxVgrydxT-4

**Comment by funtigr** [comment]
Now the User can be deleted from the Public Cloud Users Dashboard:
<img width="1465" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1MrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6d9e0e74916eca6d3969321d88424bac1a638354/image.png" alt="image.png" />
@Kolezhanchik 
Another concern here: when the user clicks Delete icon the deleted entry doesn't disappear until the page is refreshed. That could scare or confuse the users because they are used to see immediate result in other web interfaces.
