### ISSUE TITLE
Public Cloud Edit Request email now needs to be an Edit Summary email

### ISSUE THREAD

**Issue by Amritpal-Nijjar** [bcgov/platform-services-registry#1889]
Because the public cloud does not have an approval process for an "edit request" we will modify the current edit request email to be an "edit summary" email that gets sent to the user. The comments box in this Edit Summary email will be useful to alert the po/tl/stl of why the changes were made on the registry.

**Comment by funtigr** [comment]
Now we have a summary of changes in the email. 
<img width="1005" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1kxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d23165b6fb362799067acbd2d82eebc0f0ad5cf/image.png" alt="image.png" />

I found a bit confusing the button that is called "View Changes" above the Summary of changes. Instead of scrolling to see the changes I instinctively click the button. 
Maybe we could rename the button or add some header (Summary of changes) or add text: "You can see the changes in the Registry by clicking the button or see the Summary of changes below." 
<img width="1005" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL28xQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--14d5571804e3b05cc0be6035895476641901f1e1/image.png" alt="image.png" />
