### ISSUE TITLE
remove product related users from aws roles admin panel

### ISSUE THREAD

**Issue by Kolezhanchik** [bcgov/platform-services-registry#1941]
remove product related users from aws roles admin panel
public team changed the idea of admins role users dashboard

**Comment by funtigr** [comment]
@Kolezhanchik There are still roles in Admins tab of AWS User Dashboard. Is it by design of this feature?
<img width="1479" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3BWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--091f11df1e50394b4c938959db66109ff1bf7cf9/image.png" alt="image.png" />

**Comment by Kolezhanchik** [comment]
@funtigr these are aws-role admins
