### ISSUE TITLE
[Refactoring] Convert list pages to client components (Private Product Dashboard)

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#2528]
We want to transform list pages into client components to enhance page loading and eliminate inconsistencies with query parameters.
- Private Product Dashboard: https://dev-pltsvc.apps.silver.devops.gov.bc.ca/private-cloud/products/all

**Comment by funtigr** [comment]
@junminahn 
If User goes to page 5 (with 10 products peg page) and then applies filter (like KLAB products) he sees empty list, because Dev now has 39 KLAB products. The writing in the bottom says "Showing 41 to 39 of 39 results". 
<img width="1471" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW1VQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9622a3e93beaffd748b159492162921041a0ad7/image.png" alt="image.png" />

**Comment by funtigr** [comment]
Both issues above are fixed.
