### ISSUE TITLE
Public Cloud - Email Scenario #2

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#2570]
**Public Cloud**

- [x] Scenario 2, edit request is sending a provisioned email, this should not be the case. Only send the edit summary email
- [x] Ask public cloud if there is a callback for an edit. Explore possibility of sending an email before the edit is provisioned and sends the edit summary email. Update docs if we do implement this change
- [x] Scenario 3, change subject of rejection email to say something like "Request has been rejected for [product name]"
- [x] Scenario 3, for reject delete email, add product details section

**Comment by Amritpal-Nijjar** [comment]
Asked Public Cloud if there is a callback when an edit request is received, and confirmed that there is not one. There is only a callback when the provisioner completes the request.

**Comment by funtigr** [comment]
1. Summary only instead of two emails - implemented,
2. Change Rejected email name:
@Amritpal-Nijjar 
The phrase in the header is in single quotes for both Create Rejected and Delete Rejected emails: 
<img width="972" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1RZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ae8c669d51b9c4c10fde3416a2dd8ff260843e2/image.png" alt="image.png" />
3. The section with product data is added to Delete Rejected email.
