### ISSUE TITLE
Add 'X' button to clear Search text field

### ISSUE THREAD

**Issue by funtigr** [bcgov/platform-services-registry#2891]
Now if you type a prompt in Search field, in order to delete it you have to delete it manually. 
I propose to add an 'X' button to clear the Search text field in one click.
Example from GitHub:
<img width="652" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNllGQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e30cc72bfa57fbc76c495ec6ef8c2b826b7d4e3/image.png" alt="image.png" />

**Comment by junminahn** [comment]
pr: https://github.com/bcgov/platform-services-registry/pull/3290

**Comment by Amritpal-Nijjar** [comment]
Functionality wise it works as expected. Here are a few UX/UI improvements we can make
1) Only display the X icon to clear the field if there is something to clear. Currently a user can click the X icon to do nothing with no feedback
2) Try to use consistent icons. Instead of the square version, we can opt for the default `iconX`. See here for example: https://github.com/bcgov/platform-services-registry/blob/main/app/components/comments/CommentForm.tsx#L158
3) Almost all buttons currently have a hover effect to indicate that something is clickable, we can do the same for this clear button. See here for example: https://github.com/bcgov/platform-services-registry/blob/main/app/components/comments/CommentForm.tsx#L159

**Comment by junminahn** [comment]
@Amritpal-Nijjar, all good feedback! Technically, this ticket should be accepted as is, and a new one should be created for the improvements.

Regarding `#2`, I tried both options, and the `square` one looks better to me, so let's leave it as it is; especially, the example screenshot has the square one.

For the new ticket, we could add:
1. Display the `X` button only if there is text.
2. Display a hover tooltip explaining the button's function if it is displayed.
