### ISSUE TITLE
Update the two public API endpoints to

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#3220]
Update the two public API endpoints to:
1. Include product ID and user IDs in the payload.
2. Add search parameters: `active`, `ministry`, `provider`, and `cluster`.

**Comment by junminahn** [comment]
<img width="426" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem1WQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5f0004a35d303dc61f5e16139f690bebcd023d2c/image.png" alt="image.png" />

**Comment by junminahn** [comment]
pr: https://github.com/bcgov/platform-services-registry/pull/3232

**Comment by Kolezhanchik** [comment]
works as expected can see product ID and PO/TLs IDs in the payload
<img width="1552" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2lWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--61d0aae9824f36155a6d0c93d198b0fb6566d7a0/image.png" alt="image.png" />

search parameters 'cluster` and ministry have `Enum` type instead of string, `status` also have `Enum` type and not limited with`active` only
