### ISSUE TITLE
Grant Admin and Private-Admin permission to uncheck Temporary Label for Temporary Products

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#3242]
Grant Admin and Private-Admin permission to uncheck Temporary Label for Temporary Products

**Comment by funtigr** [comment]
It works as expected except one detail. When I uncheck Temporary Label, I need to submit an Edit Request and leave a comment, even though I do it within an Admin role. And after I submit it I got a message 'We received your request'. 
That's not very intuitive but fine for now as it will be used only for admins. But if there is an easy way to fix it to be an Approve button instead of Submit Request it would be more logical.

**Comment by funtigr** [comment]
The Title of the modal window is a bit confusing, when admin unchecks the temporary status. It says: "Are you sure you want to set this product as a temporary product set?"
<img width="1462" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzRKQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f0679246b81e381608c0ead80e8470206bde738b/image.png" alt="image.png" />

**Comment by funtigr** [comment]
Fixed:
<img width="861" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL29PQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d300f9a3af8ac3a6231f27f5c3023018532f5021/image.png" alt="image.png" />
