### ISSUE TITLE
Add new justification field for quota increase requests

### ISSUE THREAD

**Issue by alexandralloyd** [bcgov/platform-services-registry#3369]
**Describe the issue**
Add justification question for all quota increases. This field will require inputs. It will only appear (at the end of the quota section) when a user selects a higher value from the drop down. This will go alongside the new contact fields for requesters (see 3368).

**Rational/Why**
As an admin, I want users to give me detailed and practical information as to why they need more resources. 

**Additional Context**
- Happening in the Registry<img width="1587" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1h4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--20c37d4212d29f596b35455c07c0258f7e30e2a7/Screenshot%202024-07-18%20at%2012.53.54%20PM.png" alt="Screenshot 2024-07-18 at 12.53.54 PM.png" />

**Dependencies**
- Once this goes live we will have to update our documentation
- We will also have to change the text of the current modal comment box to be reflective of this change. I'd suggest we change the text to be more general, something like "If you have any additional comments about the request, add them here."

**Tests**

**Definition of done/Acceptance Criteria**

- Clear description of the intended final result
- Acceptance criteria that describes the action a User Acceptance Tester would be trying to see if the work is complete

**Comment by junminahn** [comment]
@funtigr the admin will check its quota contacts and justification in the summary tab:
<img width="1049" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUFKQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c0b6802c8eca306a0002dfccfe13279742b52a6/image.png" alt="image.png" />

**Comment by funtigr** [comment]
Justification field appears if the User chooses quota increase in one of dropdowns. It cannot be empty otherwise doesn't allow to Submit the request.
The field is not shown in the email and decision/product/request page but is shown on Summary tab of Request. And later on Summary tab of Request, clicked in Requests tab of Product:
<img width="1468" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3NKQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d1851dd3e916696a6bd948cfa2d1cf7a1520b8c4/image.png" alt="image.png" />
