### ISSUE TITLE
Public Cloud eMOU Form - EA signing process

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#3499]

**Comment by junminahn** [comment]
[OCIO and (TEAM NAME)- AWS (1).docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGliQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--845cfb4fdb6bbbcdc950d9d9b45785a117aa2dd8/OCIO%20and%20%28TEAM%20NAME%29-%20AWS%20%281%29.docx)

**Comment by funtigr** [comment]
The `team name` is fixed. All the text issues correspond to the example document, provided above.
The `AWS` instead of `MS Azure` will be tackled in corresponding later task.
<img width="1468" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXljQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--14d0a3d5529e3b78ec4839837f38381971ce81b8/image.png" alt="image.png" />
