### ISSUE TITLE
Evaluate future automation opportunities for project provisioning through Registry

### ISSUE THREAD

**Issue by mitovskaol** [bcgov/platform-services-registry#361]
Review which of [these enhancements](https://github.com/BCDevOps/OpenShift4-Migration/issues/73) can be automated with the provisioning bot and added to a project at the time of its creation.

**Comment by IanKWatts** [comment]
See below for responses to the feature requests...

_1) Pre-configured role bindings: when deploying a new set of services, role bindings need to be configured in order to follow the recommended pattern of storing builds/images in the tools namespace, and deployments in dev/test/prod._

Not all teams use the tools/dev/test/prod model and the Platform Services Team prefers that role bindings be managed by project teams.


_2) Pre-configured "general" NSPs: there are a couple of NSPs that could be configured by default when generating a name set, as not having them in place will cause things to not work at all. In particular, the NSP allowing pods to talk to the K8S api should be pre-configured in all namespaces (tools/dev/test/prod), while the NSP allowing builds to pull from the internet (Git, NPM, PyPy, NuGet, etc.) should be pre-configured for the tools namespace._

Now that the OpenShift platform is using Kubernetes network policies instead of Aporeto, this is no longer an issue.  Egress traffic is now allowed by default and the Aporeto zero-trust policy is not in effect.


_3) Pre-configured pull secrets to make using Artifactory (or other Docker image registries) transparent._

It has been suggested that we use cluster-wide pull credentials so that project teams do not have to manage this on their own, but this presents other problems, namely that the platform team would be responsible for the management of the credentials.
Alternatively, if pull secrets were automatically set up and managed by ArgoCD for project teams, that would interfere with teams managing secrets on their own.
The Platform Services Team will consider options for this in the future, but for now will not manage pull secrets for teams.


_4) The OCP3 way of copying the login command, without having additional pop-up windows and links to click seemes more efficient/user friendly._

Unfortunately, this is a feature of OpenShift 4 and is not something that we can change.  It was implemented as a security feature.  In OpenShift 3 the token could be copied with a single click, even if the user's session was already expired (the token might still be valid after session expiration).   In OpenShift 4 the token cannot be displayed when the session is expired, although this is slightly less convenient.
