### ISSUE TITLE
Revisit email workflows & templates

### ISSUE THREAD

**Issue by junminahn** [bcgov/platform-services-registry#3747]

**Comment by funtigr** [comment]
Looked through all the emails. 
The only small thing I found is that when Reviewer receives the email about `Request waiting for review`, the footer says:
> If you have any questions, send us a message at PlatformServicesTeam@gov.bc.ca. We'd love to hear from you.
Platform Services Team

So it kind of has a call for Platform Admins to direct their questions to their own email.
<img width="815" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXpjQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b6e346e74e0df48c0b824224e8813fb1109c15b7/image.png" alt="image.png" />

Another thing is now in the Create Request Email in Public Cloud we have the text that provisioning of AWS would take 3-5 minutes. I suppose that's not true, it would take longer, because their process is less automated and more complex.
Maybe we would return old text and templates for the Public Cloud flow?
<img width="1342" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBempjQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9d63fe6fe7601f7df921a10073b44cdef9089c1c/image.png" alt="image.png" />

**Comment by funtigr** [comment]
Fixed:
Edit Request:
<img width="817" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGpmQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--089f6e16c5a1d032c5bc4b6a6505740a955f3f18/image.png" alt="image.png" />

Create Request:
<img width="812" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG5mQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c20247295e79ddd31640f76390b22206e110bbf/image.png" alt="image.png" />

Delete Request:
<img width="815" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHZmQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0af2d7094a78646142e029b5ed492eaae29dd6f1/image.png" alt="image.png" />
