### ISSUE TITLE
Web and email have reversed PO and TC

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#387]
**Describe the issue**
The PO and TC are reversed on the notification email(s). For example, the web shows the PO as person A and TC as person B but the emails have A and B reversed.

<img width="1043" alt="Screen Shot 2021-04-29 at 10 00 52 AM" src="https://user-images.githubusercontent.com/390891/116590156-4807c780-a8d2-11eb-885c-8a3359b3035b.png">

**Definition of done**
The email(s) and web have matching data.

**Comment by jleach** [comment]
@yhfreeman @sbathgate Might be a quick fix we can squeeze into this sprint. I've had once person confused by it. Most ppl don't seem to notice.

**Comment by sbathgate** [comment]
Just took a peek at this, and it should be a relatively quick fix. [Lines 66-67](https://github.com/bcgov/platform-services-registry/blob/master/api/src/libs/messaging.ts#L66-L67) currently just pop out the contacts from slot 0 and 1 as captured [here](https://github.com/bcgov/platform-services-registry/blob/master/api/src/libs/messaging.ts#L93-L94).

It should be as simple as adjusting this logic to assign the variables off of the roleId rather than array order, to ensure this doesn't happen.
