### ISSUE TITLE
Research Spike: Evaluate the feasibility of "light" project set (less than 4 accounts) provisioning for Private Cloud

### ISSUE THREAD

**Issue by lukegonis** [bcgov/platform-services-registry#3965]
**Describe the issue**
This feature would enable teams to select which of the dev, test, tools and prod namespaces their want in their project set, rather than getting all four by default, a user can select any number of namespaces from 1 to 4 with no mandatory namespace as long as there is one selected. 

TBD - we should clarify if there will be any mandatory namespace(s). We need to understand the pricing plan and requirements for having any particular namespace type. 

**Rational/Why**
Teams may not want to pay for all four name spaces in their project set. 

**Additional Context**

- this functionality exists in public cloud.

**Dependencies**

- Internal, external, who to talk to if more information is needed

**Tests**

**Definition of done/Acceptance Criteria**

- [ ] - get a decision about this registry feature if we are proceeding with this change
- [x] - confirm all dependencies with Provisioner and Ian 

If the decision will be "yes" to proceed with this change: 
- [ ] - define the UI changes in the Registry
- [ ] - define NATS messages settings

**Comment by IanKWatts** [comment]
* The provisioner correctly processes a NATS message that contains less than four namespaces.  The '.namespaces' list of the message should include only those namespaces that have been requested.
* Vault access setup works

Zero quota support has been added to the provisioner.  To demonstrate how to set up the NATS message, first here is a normal record from the namespaces list:
```
  {
    "name": "e95e91-tools",
    "quota": {
      "cpu": "cpu-request-1-limit-2",
      "memory": "memory-request-2-limit-4",
      "storage": "storage-1",
      "snapshot": "snapshot-5"
    },
    "quotas": {
      "cpu": {
        "requests": 1,
        "limits": 2
      },
      "memory": {
        "requests": "2Gi",
        "limits": "4Gi"
      },
      "storage": {
        "block": "1Gi",
        "file": "1Gi",
        "backup": "1Gi",
        "capacity": "1Gi",
        "pvc_count": 60
      },
      "snapshot": {
        "count": 5
      }
    }
  }
```
Now here is the same namespace configured for zero quota:
```
  {
    "name": "e95e91-tools",
    "quota": {
      "cpu": "cpu-request-0-limit-0",
      "memory": "memory-request-0-limit-0",
      "storage": "storage-0",
      "snapshot": "snapshot-0"
    },
    "quotas": {
      "cpu": {
        "requests": 0,
        "limits": 0
      },
      "memory": {
        "requests": 0,
        "limits": 0
      },
      "storage": {
        "block": 0,
        "file": 0,
        "backup": 0,
        "capacity": 0,
        "pvc_count": 0
      },
      "snapshot": {
        "count": 0
      },
      "pods": 0
    }
  }
```
Note that I have added quotas.pods, set to zero.  It's not normally included, because the default value is set in the provisioner and we do not allow users to update this setting via the registry.

Custom resources, such as GitOpsTeams and Sysdig-Teams, can still be created and processed in a tools namespace with a zero quota.

**Comment by junminahn** [comment]
@IanKWatts 
Thank you for the prompt research. Since a `zero quota (empty) namespace` is possible, we can offer the project team the option to scale down the size of unused namespaces rather than providing a checkbox to select which namespaces they want. This way, we can maintain the current workflow, which creates four separate namespaces (dev, test, prod, and tools), while giving them the option of an empty quota to save budget on unused namespaces. This simplifies the process and avoids handling cases where namespaces need to be removed from existing projects.

**Comment by Iryna-Kaplun** [comment]
Olena's response from Oct 11, 2024: 
Yes, zero quota namespaces will not have any cost. I like this option too since we can enable it easily but just adding an additional option in the quota dropdown

**Comment by junminahn** [comment]
After further research and discussion, we've decided to proceed with the second option: adding an empty quota option to the dropdowns. This approach maintains the current workflow and simplifies development efforts by avoiding the use of namespace checkboxes.
