### ISSUE TITLE
Displaying subnet info for project namespaces in Registry UI

### ISSUE THREAD

**Issue by golebu2020** [bcgov/platform-services-registry#4238]
**Description**  
- Display /26 CIDR subnet information for project namespaces in the registry UI (Emerald Clusters only).

**Technical Details**  
- Please use the following `oc command` to implement this feature: 

`oc get namespace <namespace> -o jsonpath='{.metadata.annotations.ncp\/subnet-0}{"\n"}'`

**Definition of Done (DOD)**  
- The /26 CIDR subnet information of the project namespace (Emerald clusters only)  is displayed on the product page

**Comment by golebu2020** [comment]
okay

**Comment by funtigr** [comment]
As I see from the task description, we should show this information for Emerald cluster only?
Because we now have that for any cluster (e.g. KLAB on screenshot below):
<img width="1487" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUh5Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9308376fe9e5c765aceaa0879da67f25cd23d77f/image.png" alt="image.png" />

**Comment by funtigr** [comment]
Also after we made a deploy to prod, the Emerald cluster products don't show subnet information. My assumption is we need to add some environment variables for that:
<img width="1476" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFR6Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c6857af558282802103d8ffaab1fa41b4fc47cc6/image.png" alt="image.png" />

**Comment by funtigr** [comment]
We will add token for Prod after we test Zhanna's task about Quota auto-approval.
