### ISSUE TITLE
Create separate resource quotas for CPU vs RAM vs Storage

### ISSUE THREAD

**Issue by mitovskaol** [bcgov/platform-services-registry#514]
At this moment CPU/RAM and Storage resources in Openshift 4 Platform are all bundled together into resource quota as described [here](https://developer.gov.bc.ca/Project-Resource-Quotas-in-BC-Gov's-PaaS-(Openshift-4-Platform)). However, it became obvious that CPU and storage resource needs for projects are not correlated as often projects need an increase in just one resource category. 

We need to split the CPU/RAM/Storage resource quotas into the CPU/RAM and Storage resource quotas and enable projects to request an increase in either quota separately.

DoD:
- Support for CPU/RAM and Storage quotas (the amount of resources in each small/medium/large quota size will stay the same) is added to the Project Registry and in the provisioner. Teams are able to request increase either in CPU/RAM resource category or Storage separately.

**Comment by j-pye** [comment]
@mitovskaol @juhewitt It might be better to go ahead and split quotas for all resources and all environments like we had in the early days of the Registry. 

If you'd still like to group CPU / Mem into one bundle I think that's fine, however the technical implementation should support the splitting of all resources even if the business login displayed on the front end is grouped. This also makes it easier to add custom quota support to the registry later if it's needed. It would be great to eventually support an admin interface to set quotas outside of the T-Shirt sizes so that the Registry can remain the single source of truth, and so that the provisioner does not have hardcoded quotas for select project sets. (Right now these custom quotas can not be displayed in the report generated by the Registry)

**Comment by IanKWatts** [comment]
@mitovskaol @juhewitt @j-pye I agree with Mr. Pye that we should maintain some flexibility in the resource allocation, even if the front end simplifies the selection.  There will always be special cases.

**Comment by mitovskaol** [comment]
@j-pye @IanKWatts  I agree with splitting the current quotas into 3 separate quotas for CPU, RAM and Storage so that each resource can be increased independently.

**Comment by w8896699** [comment]
![Screen Shot 2021-09-24 at 4.09.48 PM.png](https://images.zenhubusercontent.com/5d6ffb905ec50a5aa4201bcb/9d901bb6-479d-4413-8aec-dbd6c1a0bdac)
Hi @marthaedwards, @mitovskaol , do you guys like this UI?

**Comment by mitovskaol** [comment]
Can  you please add "Quota Size" label to all 3 dropdowns and remove it from the top of the section where it is now under Quota information.

**Comment by w8896699** [comment]
Maybe like this? ![Screen Shot 2021-09-24 at 4.36.51 PM.png](https://images.zenhubusercontent.com/5d6ffb905ec50a5aa4201bcb/af1ff126-b507-464c-b0f9-c5a1e2f6be67)

**Comment by mitovskaol** [comment]
Yes, this looks much better. Let's just remove the word "Current" and it will look perfect :)

**Comment by lukegonis** [comment]
Completed and in production
