### ISSUE TITLE
Registry Dashboard CSV download is broken in Chrome

### ISSUE THREAD

**Issue by ll911** [bcgov/platform-services-registry#792]
**Describe the issue**
Registry Dashboard CSV download is broken in Chrome 106.0.5249.119

**Additional context**
Click the download button, screen blink, and nothing downloaded first time.
open dev console, reload page, re-down works. 

**Definition of done**
dashboard report can be downloaded without dev console open.

**Comment by okanji** [comment]
Hi @ll911, thanks for reaching out and creating this ticket. We have seen it and would like to sort this out so that you can use the CSV feature. I tried it in my chrome and while the UI is a bit sticky/ delayed, it does work so maybe we can hop on a call sometime and share screens so I can get a sense of the issue?

Thanks
