### ISSUE TITLE
On the Product Tab at Edit Request make button non-clickable if the user did not change any of the fields' values.

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#918]
**Describe the bug**
On the Product Tab if the user did not change any of the values of the product the button allows to submit an Edit Request. That leads to a bug which doesn't allow to approve or reject such request.

**Environment**
Met on various instances.

**To Reproduce**
Steps to reproduce the behaviour:

Go to the Product Tab.
Click on one of the products.
Do not touch any fields.
Click Submit in the bottom of the page.
Further steps optional, to see the bug from Admin side:
5. Login as admin.
6. Go to the mentioned earlier request.
7. Scroll down to see the grayed out buttons.

**Expected behaviour**
The buttons are grayed out on the user side if he did not change any values on the Edit Request page.

**Comment by okanji** [comment]
@calbertan and I met regarding this ticket. After going through the code I realized that this was in fact a very complicated issue due to complex form validation logic with material UI. Being that it is not critical, I decided that it would be better to direct Christopher's time to a more critical ticket. 

Also, we are using a different form validation method for the new designs with tailwindui components that makes form validation significantly easier. 

It is great that @calbertan got to work on this to understand how complex form validation is, but going forward we can use him on some more important tickets.
